#This file will try to unzip the package
name: unzip the folder
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
          description: 'Want to proceed'
          default: 'No'
          #required: true
          type: string
          
jobs:
  proceed:
     runs-on: ubuntu-latest
     steps: 
       - name: unzip the folder
         run: echo 'want to proceed ${{ inputs.name }}
